# This script will cvreate sudo users along with passwordless authenciation
---
- hosts: localhost
  become: yes
  connection: ssh
  tasks:
         - name: Add user
           user: 
             name: "{{ item }}"
             state: present
           with_items:
             - test1
             - test2
             - test3
         - name: Validate the sudoers file before saving
           ansible.builtin.lineinfile:
              path: /etc/sudoers
              state: present
              insertafter: "root    ALL=(ALL)       ALL"
              line: "{{ item }}    ALL=(ALL)       ALL"
              validate: /usr/sbin/visudo -cf %s
           with_items:
             - test1
             - test2
             - test3