# This script will cvreate sudo users along with passwordless authenciation
---
- hosts: linux_host
  become: yes
  connection: ssh
  tasks:
         - name: Add user
           user: 
             name: "{{ item }}"
             state: present
           with_items:
             - test1
             - test2
             - test3
         - name: Validate the sudoers file before saving
           ansible.builtin.lineinfile:
              path: /etc/sudoers
              state: present
              firstmatch: yes
              line: "{{ item }} ALL=(ALL) ALL"
              insertafter: "^root ALL=(ALL) ALL"
              validate: /usr/sbin/visudo -cf %s
           with_items:
             - test1
             - test2
             - test3
